export const environment = {
  production: true,
  courses_baseUrl: 'https://educationplatform-juhi.onrender.com/api/v1/courses',
  loginUrl: 'https://educationplatform-juhi.onrender.com/api/v1/auth/signin',
  signupUrl: 'https://educationplatform-juhi.onrender.com/api/v1/auth/signup',
  contact_baseUrl: 'https://educationplatform-juhi.onrender.com/api/v1/contacts',
  moduleTest_baseUrl: 'https://educationplatform-juhi.onrender.com/api/v1/module-tests',
  pdf_baseUrl: 'https://educationplatform-juhi.onrender.com/api/v1/pdfs',
  test_baseUrl: 'https://educationplatform-juhi.onrender.com/api/v1/tests',
  userUrl: 'https://educationplatform-juhi.onrender.com/api/v1/test/user',
  pmUrl: 'https://educationplatform-juhi.onrender.com/api/v1/test/mod',
  adminUrl: 'https://educationplatform-juhi.onrender.com/api/v1/test/admin',
  allUrl: 'https://educationplatform-juhi.onrender.com/api/v1/test/all',
  allUserUrl: 'https://educationplatform-juhi.onrender.com/api/v1/user/all',
  delete:'https://educationplatform-juhi.onrender.com/api/v1/user/delete',
  addUser: 'https://educationplatform-juhi.onrender.com/api/v1/user/save',
  uploadUrl: 'https://educationplatform-juhi.onrender.com/api/v1/upload',
  baseUrl: 'https://educationplatform-juhi.onrender.com/api/v1/user',
};
