export const environment = {
  production: false,
  courses_baseUrl: 'http://localhost:8080/api/v1/courses',
  loginUrl: 'http://localhost:8080/api/v1/auth/signin',
  signupUrl: 'http://localhost:8080/api/v1/auth/signup',
  contact_baseUrl: 'http://localhost:8080/api/v1/contacts',
  moduleTest_baseUrl: 'http://localhost:8080/api/v1/module-tests',
  pdf_baseUrl: 'http://localhost:8080/api/v1/pdfs',
  test_baseUrl: 'http://localhost:8080/api/v1/tests',
  userUrl: 'http://localhost:8080/api/v1/test/user',
  pmUrl: 'http://localhost:8080/api/v1/test/mod',
  adminUrl: 'http://localhost:8080/api/v1/test/admin',
  allUrl: 'http://localhost:8080/api/v1/test/all',
  allUserUrl: 'http://localhost:8080/api/v1/user/all',
  delete:'http://localhost:8080/api/v1/user/delete',
  addUser: 'http://localhost:8080/api/v1/user/save',
  uploadUrl: 'http://localhost:8080/api/v1/upload',
  baseUrl: 'http://localhost:8080/api/v1/user',
  newsUrl: 'http://localhost:8080/api/v1/news',

};
